# This file auto-generated by Garnet OS Make builder.  Don't modify directly!!!

# This value is unescaped.  Either quote the value or escape special characters when you use it.
ifeq ($(TOOLS_DIR), )
   TOOLS_DIR = C:/dev/access/garnet/suite/PalmOSTools/
endif

# This value is unescaped.  Either quote the value or escape special characters when you use it.
ifeq ($(SDK_LOCATION), )
   SDK_LOCATION = C:/dev/access/garnet/suite/sdk-5r4/
endif

ifeq ($(SDK_VERSION), )
   SDK_VERSION = sdk-5r4
endif

ifeq ($(DATABASE_RESET), )
   DATABASE_RESET = 
endif

ifeq ($(DATABASE_BUNDLE), )
   DATABASE_BUNDLE = 
endif

ifeq ($(CREATOR_ID), )
   CREATOR_ID = REFL
endif

ifeq ($(DATABASE_BACKUP), )
   DATABASE_BACKUP = -b
endif

ifeq ($(DB_TYPE), )
   DB_TYPE = appl
endif

ifeq ($(PROJECT_VERSION), )
   PROJECT_VERSION = 10100
endif

ifeq ($(DATABASE_PROTECT), )
   DATABASE_PROTECT = 
endif

ifeq ($(SDK), )
   SDK = com.palmsource.eclipse.sdk.palmos5
endif

ifeq ($(DB_NAME), )
   DB_NAME = Reflect
endif

ifeq ($(DATABASE_HIDDEN), )
   DATABASE_HIDDEN = 
endif

ifeq ($(DATABASE_VERSION), )
   DATABASE_VERSION = 1
endif

ifeq ($(OS_API), )
   OS_API = 68K
endif

ifeq ($(PROJECT_TYPE), )
   PROJECT_TYPE = appl
endif

ifeq ($(ARTIFACT_NAME), )
   ARTIFACT_NAME = Reflect
endif

